export const PLANS = {
    FREE: "FREE",
    PRO_MONTHLY: "PRO_MONTHLY",
    PRO_YEARLY: "PRO_YEARLY",
};

export const PLAN_CONFIG = {
    FREE: {
        price: 0,
        interval: "EVERY_30_DAYS",
        label: "Free Plan",
        features: ["price", "compare_price", "cost", "status"],
    },
    PRO_MONTHLY: {
        price: 15.0,
        interval: "EVERY_30_DAYS",
        label: "Pro Monthly",
        features: [
            "price",
            "compare_price",
            "cost",
            "status",
            "inventory",
            "tags",
            "metafield",
            "weight",
            "vendor",
            "product_type",
            "requires_shipping",
            "taxable",
            "sales_channels",
            "market_publishing",
            "market_price",
            "add_variants",
            "add_options",
            "delete_variants",
            "delete_products",
            "sort_variants",
            "reorder_options",
            "connect_locations",
            "images",
            "manual_collection",
            "option1_name",
            "option2_name",
            "option3_name",
            "handle",
            "body_html",
            "title",
            "template_suffix",
            "published",
            "seo_title",
            "seo_description",
            "sku",
            "barcode",
            "inventory_policy",
            "google_product_category",
            "google_age_group",
            "google_gender",
            "google_color",
            "google_size",
            "google_material",
            "google_pattern",
            "google_condition",
            "google_mpn",
            "google_brand",
            "google_custom_label_0",
            "google_custom_label_1",
            "google_custom_label_2",
            "google_custom_label_3",
            "google_custom_label_4",
            "hs_code",
            "country_of_origin"
        ],
    },
    PRO_YEARLY: {
        price: 150.0,
        interval: "ANNUAL",
        label: "Pro Yearly",
        features: [
            "price",
            "compare_price",
            "cost",
            "status",
            "inventory",
            "tags",
            "metafield",
            "weight",
            "vendor",
            "product_type",
            "requires_shipping",
            "taxable",
            "sales_channels",
            "market_publishing",
            "market_price",
            "add_variants",
            "add_options",
            "delete_variants",
            "delete_products",
            "sort_variants",
            "reorder_options",
            "connect_locations",
            "images",
            "manual_collection",
            "option1_name",
            "option2_name",
            "option3_name",
            "handle",
            "body_html",
            "title",
            "template_suffix",
            "published",
            "seo_title",
            "seo_description",
            "sku",
            "barcode",
            "inventory_policy",
            "google_product_category",
            "google_age_group",
            "google_gender",
            "google_color",
            "google_size",
            "google_material",
            "google_pattern",
            "google_condition",
            "google_mpn",
            "google_brand",
            "google_custom_label_0",
            "google_custom_label_1",
            "google_custom_label_2",
            "google_custom_label_3",
            "google_custom_label_4",
            "hs_code",
            "country_of_origin"
        ],
    },
};

export function isProPlan(planName: string | null) {
    if (!planName) return false;
    const p = planName.toUpperCase().replace("_", " "); // Normalize to spaces
    // Use includes to handle cases like "PRO MONTHLY (DISCOUNT applied)"
    return p.includes("PRO") || p.includes("ADVANCED");
}
