// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/webhooks/gdpr": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/api/cron": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/support-admin/:shopDomain": {
    params: {
      "shopDomain": string;
    };
  };
  "/app/support-admin": {
    params: {};
  };
  "/app/owner-dashboard": {
    params: {};
  };
  "/app/email-preview": {
    params: {};
  };
  "/app/preview-data": {
    params: {};
  };
  "/app/create-demo": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/plans": {
    params: {};
  };
  "/app/tasks": {
    params: {};
  };
  "/app/tasks/:id": {
    params: {
      "id": string;
    };
  };
  "/app/tasks/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/webhooks/gdpr" | "/auth/login" | "/api/cron" | "/auth/*" | "/app" | "/app/support-admin/:shopDomain" | "/app/support-admin" | "/app/owner-dashboard" | "/app/email-preview" | "/app/preview-data" | "/app/create-demo" | "/app/additional" | "/app/settings" | "/app/plans" | "/app/tasks" | "/app/tasks/:id" | "/app/tasks/new";
  };
  "routes/webhooks.customers.data_request.jsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.jsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.jsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/webhooks.gdpr.jsx": {
    id: "routes/webhooks.gdpr";
    page: "/webhooks/gdpr";
  };
  "routes/auth.login.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/api.cron.ts": {
    id: "routes/api.cron";
    page: "/api/cron";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/support-admin/:shopDomain" | "/app/support-admin" | "/app/owner-dashboard" | "/app/email-preview" | "/app/preview-data" | "/app/create-demo" | "/app/additional" | "/app/settings" | "/app/plans" | "/app/tasks" | "/app/tasks/:id" | "/app/tasks/new";
  };
  "routes/app.support-admin.$shopDomain.jsx": {
    id: "routes/app.support-admin.$shopDomain";
    page: "/app/support-admin/:shopDomain";
  };
  "routes/app.support-admin._index.jsx": {
    id: "routes/app.support-admin._index";
    page: "/app/support-admin";
  };
  "routes/app.owner-dashboard.tsx": {
    id: "routes/app.owner-dashboard";
    page: "/app/owner-dashboard";
  };
  "routes/app.email-preview.tsx": {
    id: "routes/app.email-preview";
    page: "/app/email-preview";
  };
  "routes/app.preview-data.tsx": {
    id: "routes/app.preview-data";
    page: "/app/preview-data";
  };
  "routes/app.create-demo.tsx": {
    id: "routes/app.create-demo";
    page: "/app/create-demo";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.plans.tsx": {
    id: "routes/app.plans";
    page: "/app/plans";
  };
  "routes/app.tasks.tsx": {
    id: "routes/app.tasks";
    page: "/app/tasks" | "/app/tasks/:id" | "/app/tasks/new";
  };
  "routes/app.tasks._index.tsx": {
    id: "routes/app.tasks._index";
    page: "/app/tasks";
  };
  "routes/app.tasks.$id.tsx": {
    id: "routes/app.tasks.$id";
    page: "/app/tasks/:id";
  };
  "routes/app.tasks.new.tsx": {
    id: "routes/app.tasks.new";
    page: "/app/tasks/new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.jsx");
  "routes/webhooks.gdpr": typeof import("./app/routes/webhooks.gdpr.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.jsx");
  "routes/api.cron": typeof import("./app/routes/api.cron.ts");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.support-admin.$shopDomain": typeof import("./app/routes/app.support-admin.$shopDomain.jsx");
  "routes/app.support-admin._index": typeof import("./app/routes/app.support-admin._index.jsx");
  "routes/app.owner-dashboard": typeof import("./app/routes/app.owner-dashboard.tsx");
  "routes/app.email-preview": typeof import("./app/routes/app.email-preview.tsx");
  "routes/app.preview-data": typeof import("./app/routes/app.preview-data.tsx");
  "routes/app.create-demo": typeof import("./app/routes/app.create-demo.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.plans": typeof import("./app/routes/app.plans.tsx");
  "routes/app.tasks": typeof import("./app/routes/app.tasks.tsx");
  "routes/app.tasks._index": typeof import("./app/routes/app.tasks._index.tsx");
  "routes/app.tasks.$id": typeof import("./app/routes/app.tasks.$id.tsx");
  "routes/app.tasks.new": typeof import("./app/routes/app.tasks.new.tsx");
};